language: cpp

compiler: gcc
env:
  global:
    - COMPILER=g++-4.9

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - valgrind
    
before_install:
  - git clone https://github.com/eclipse/paho.mqtt.c.git
  - cd paho.mqtt.c
  - mkdir build && cd build
  - cmake -DPAHO_WITH_SSL=FALSE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=FALSE -DPAHO_ENABLE_TESTING=FALSE
  - make && sudo make install
  - git clone https://github.com/eclipse/paho.mqtt.cpp.git
  - cd paho.mqtt.cpp
  - mkdir build && cd build
  - cmake -DPAHO_WITH_SSL=FALSE -DPAHO_MQTT_C_PATH=../../paho.mqtt.c ..
  - make && sudo make install

install:
  - sudo pip install -U "cpp-coveralls"

script:
  cmake . -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $COMPILER);
  make;
  ./test/bin/unittest;

after_success:
  coveralls --include src --gcov-options '\-lp' --gcov 'gcov-4.9';
  valgrind --error-exitcode=1 --leak-check=full ./test/bin/unittest;

